create table if not exists public.flood_readings (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null,
  station text not null,
  water_level_cm numeric not null,
  rainfall_mm numeric not null,
  alert_level text not null,
  prob_1h numeric not null,
  prob_3h numeric not null,
  prob_6h numeric not null
);

create index if not exists flood_readings_timestamp_idx
  on public.flood_readings (timestamp desc);
